### PR TITLE
Parse ES2017 by default 

### PR DESCRIPTION
**Pull request by cibernox**
This also updates to ember-cli beta, to make pass since both blueprints are on sync.

### CODE REVIEW

**Comment by rwjblue** [comment]
FYI - The failure in node 4 is due to `yarn` itself being incompatible with Node 4. 😭

**Comment by cibernox** [comment]
@rwjblue Intentionally or accidentally?

**Comment by rwjblue** [comment]
No comment from maintainers the last time I looked. I assume accidentally.

**Comment by Turbo87** [comment]
@cibernox could you rebase?

**Comment by cibernox** [comment]
@Turbo87 done

**Pull request merged**
