### PR TITLE
Add tests for the "ember test" output

### PR DESCRIPTION
**Pull request by Turbo87**
similar to https://github.com/ember-cli/ember-cli-jshint/pull/19

/cc @BrianSipple @alexlafroscia @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like @travis-ci is currently having some issues with `nvm install`...

**Comment by rwjblue** [comment]
Looks good, not sure about the CI failure though.

**Comment by rwjblue** [comment]
Ahh, I see

**Comment by Turbo87** [comment]
I restarted the job, seems to be resolved now.

**Pull request merged**
