### PR TITLE
Allow passthrough of rulesDir option to broccoli-lint-eslint

### LINKED ISSUE #150: Support Eslint --rulesdir somehow
I'm not sure what the best way to do this would be, but I'm trying to add a custom eslint rule, and can run eslint with `--rulesdir eslint_rules` where `eslint_rules/` is a directory containing custom rules. Should this be supported?

Running eslint directly with the flag works, but it fails when ember-cli runs eslint because it doesn't look for the directory.

### PR DESCRIPTION
**Pull request by thomblake**
Fixes #150

### CODE REVIEW

**Comment by Turbo87** [comment]
@thomblake do you think it's possible to test this in some way?

**Comment by Turbo87** [comment]
also please add that option to the `README`

**Comment by thomblake** [comment]
I can't think of a good way to write an automated test for this?

**Comment by Turbo87** [comment]
released as `v4.1.0`

**Pull request merged**
